config:
  validation: false

complexity:
  LongMethod:
    active: true
    threshold: 120
  CyclomaticComplexMethod:
    active: true
    threshold: 35
    ignoreSimpleWhenEntries: true
  TooManyFunctions:
    active: false
  ReturnCount:
    active: false

exceptions:
  SwallowedException:
    active: false
  TooGenericExceptionCaught:
    active: true
    allowedExceptionNameRegex: "_|(ignore|expected).*"

naming:
  FunctionNaming:
    active: false
  MatchingDeclarationName:
    active: false

style:
  MagicNumber:
    active: true
    ignoreHashCodeFunction: true
    ignoreConstantDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
    ignoreNumbers:
      - '-1'
      - '0'
      - '1'
      - '2'
      - '3'
      - '4'
      - '8'
      - '10'
      - '12'
      - '14'
      - '16'
      - '18'
      - '20'
      - '22'
      - '24'
      - '26'
      - '32'
      - '44'
      - '80'
      - '100'
      - '180'
      - '256'
      - '420'
      - '860'
    ignoreAnnotated:
      - 'Composable'
      - 'Preview'
  MaxLineLength:
    active: true
    maxLineLength: 160
  NewLineAtEndOfFile:
    active: false
  UnusedParameter:
    active: false
  ReturnCount:
    active: false
