config:
  validation: false

complexity:
  LongMethod:
    active: false
  TooManyFunctions:
    active: false
  ReturnCount:
    active: false

exceptions:
  SwallowedException:
    active: false
  TooGenericExceptionCaught:
    active: false

naming:
  FunctionNaming:
    active: false
  MatchingDeclarationName:
    active: false

style:
  MagicNumber:
    active: false
  MaxLineLength:
    active: false
  NewLineAtEndOfFile:
    active: false
  UnusedParameter:
    active: false
  ReturnCount:
    active: false
